### ISSUE TITLE
Unable to upload .zip to newly created item

### ISSUE THREAD

**Issue by Shappie112** [rkuykendall/Simplici7y#14] opened 2020-08-31 03:44 UTC
I'm trying to upload the .zip for Marathon TROJAN (fully working with the release of 1.3, woo!) but whenever I go to create the new version, it leads me to this page. See the attached screenshot.

![s7 error](https://user-images.githubusercontent.com/68048410/91680796-0ab82380-eb12-11ea-8bf4-958cd876adef.png)

I see "Uploading 0%" when I click create new version for a brief moment and then this screen. I tried uploading a different scenario to make sure it's not on my end, and everything uploaded fine.

I tried destroying and remaking the item from my profile page and I got the same result. Maybe it doesn't like the word "Trojan" all over the place? I can't figure anything out.

Let me know if you need any more info, thanks!

**Comment by Shappie112** [comment] 2020-08-31 11:45
Update: I've experienced this issue again when trying to upload Marathon Squadron. The biggest difference I can see between these two and the other things I've uploaded to S7 is the size. TROJAN and Squadron are both 145MB+ zipped, though people in the Marathon Discord have said they've had no problems uploading files that are larger than that.

**Comment by rkuykendall** [comment] 2020-08-31 13:57
Yes, the issue is size, and yes the issue is new. I recently (as in, sometime in the last year probably) put both S7 and Pfhorums behind Cloudflare, to prevent some random bot flood / attacks we were getting. Sadly, it looks like the free plan [sets a 100MB upload limit](https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN#:~:text=Cloudflare%20limits%20upload%20size%20(HTTP,to%20request%20a%20limit%20increase)). As a very temporary work-around, I've turned off Cloudflare protection for S7. Would you mind re-trying your upload and letting me know here how it goes?

**Comment by Shappie112** [comment] 2020-08-31 14:04
Yep, the upload worked, awesome! Thanks for the super quick reply and fix, I appreciate it!

**Comment by rkuykendall** [comment] 2023-06-17 19:39
Closing this as I just confirmed the re-write of S7 handles Marathon TROJAN uploads quickly and easily :)

**Closed by rkuykendall** 2023-06-17 19:39 UTC
